<?php
 // module/Application2/view/application2/application2/edit.phtml:

 $title = 'Editer une Personne';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'application2',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('nom'));
 echo $this->formRow($form->get('prenom'));
 echo $this->formRow($form->get('numeroetudiant'));

 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 
 ?>