 <?php
 // module/Application2/view/application2/application2/index.phtml:

 $title = 'My application2';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('application2', array('action'=>'add'));?>">Ajouter un nouveau Etudiant</a>
 </p>

 <table class="table">
 <tr>
     <th>Prenom</th>
     <th>Nom</th>
     <th>Num&eacute;ro d'&Eacute;tudiant </th>
     <th>Fonctions</th>
 </tr>
 <?php foreach ($application2s as $application2) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($application2->prenom);?></td>
     <td><?php echo $this->escapeHtml($application2->nom);?></td>
	 <td><?php echo $this->escapeHtml($application2->numeroetudiant);?></td>
     <td>
         <a href="<?php echo $this->url('application2',
             array('action'=>'edit', 'id' => $application2->id));?>">Modifier</a>
         <a href="<?php echo $this->url('application2',
             array('action'=>'delete', 'id' => $application2->id));?>">Supprimer</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
 
